format = """
$username\
$hostname\
$directory\
$git_branch\
$line_break\
$python\
[❯](purple) """

add_newline = false

[directory]
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
