theme = "kanagawa"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"C-h" = "jump_view_left"
"C-j" = "jump_view_down"
"C-k" = "jump_view_up"
"C-l" = "jump_view_right"

[keys.normal.space]
"minus" = "hsplit"
"\\" = "vsplit"

[keys.insert]
"C-j" = "normal_mode"
